### ISSUE TITLE
Outdated grammar and keywords list

### ISSUE THREAD

**Issue by Sei-Lisa** [textmate/secondlife-lsl.tmbundle#1]
I've been referred here as the origin of the LSL syntax highlighting for GitHub.

The LSL grammar is either outdated or bugged, as it doesn't recognize multi-line comments properly (C-style `/* ... */` comments).

Edited to add more issues I've found later (and updated the example below):

- Strings aren't highlighted.
- The only escapes recognized in strings should be `\n` and `\t`; any other escapes should just eat the `\` and take the next character literally. In particular, Unicode escapes are not recognized, and `\u` stands for `u`, but currently there seems to be a provision for treating them especially. Probably just considering the regex `\\.` as an escape would be good.
- `return` only works if followed by a space and a word, because of a space in the regex.
- The sequence '0x' followed by symbols is a syntax error, but it's highlighted as a number. This is as simple as changing the `*` qualifier after the hex numbers to a `+`.
- `function` is not a type or reserved word. It's not part of the language. `quaternion` and `event` are reserved words and are not included.

The keywords are very outdated. 

Here is an example (watch on GitHub):

```lsl
/* This would be a multi-line
    comment if it worked. */
// Single-line comments work properly, though.
default
{
    state_entry()
    {
        string texture = TEXTURE_BLANK; // constant not highlighted
        vector zero = ZERO_VECTOR; // highlighted
        texture = "abc"; // string not highlighted
        texture = "\u1234\r\n\t\"."; // Unicode escapes should not work
        llSetPrimitiveParams([]); // properly highlighted as library function
        llSetLinkPrimitiveParams(1, []); // highlighted as user function but it's a library function
        llSetLinkPrimitiveParamsFast(1, []); // highlighted as user function but it's a library function
        // The following are all caused by a space in the regex:
        return; // should be highlighted, but it only is if followed by a space and a word
        return texture; // works fine (even if it's a syntax error because this isn't a value-returning function)
        return (texture); // should be highlighted as a keyword, but it's highlighted as a user function
        return -1; // should be highlighted
    }
}
```

There are "compressed" regular expressions for a more current version of the language, for example here: https://github.com/buildersbrewery/linden-scripting-language/blob/master/kate/lsl.xml

By "compressed" I mean they use parentheses and alternation to optimize the regex, for example group identifier endings where the start is the same, e.g. instead of `ZERO_VECTOR|ZERO_ROTATION` it uses `ZERO_(?:VECTOR|ROTATION)` and so on.

**Comment by Sei-Lisa** [comment]
Updated the above post with more issues I've found. I can send a PR to fix or update the regular expressions themselves, but I can't fix the other issues. I don't have the means to test.

I've seen that several regex engines may be used. Do they all accept `(?: ... )` non-capture grouping?

**Comment by infininight** [comment]
If you can send a PR for everything you can that would be great. The two regex engines at play are Oniguruma and PCRE, there are differences but I doubt you will run into any as they are pretty obscure. The block comment is easy to fix, the main question there is do they support nesting? For example:

```
/* foo /* Is this valid? */ bar */
```

**Comment by infininight** [comment]
Just pushed a few quick changes/improvements. Block comments and operators added, string escapes reduced to those supported. Think I'm leaning to highlighting only the supported escapes, while `\` anything is technically an escaped character I think the utility of highlighting what is more likely a typo that an intention 'non'-escape might be better.

As for string matching, checking in Lightshow and here string are correctly matched already. The theme Github is using colors them a very dark blue, I presume your just missing the slight difference?

\* These will not be live on GitHub yet.
